---
version: "3.7"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        container_name: elasticsearch
        environment:
          ELASTIC_PASSWORD: adminadmin123
          discovery.type: single-node
        volumes:
          - type: bind
            source: ./elk/elasticsearch/elasticsearch.yml
            target: /usr/share/elasticsearch/config/elasticsearch.yml
            read_only: true
          - type: volume
            source: elasticsearch
            target: /usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300
        networks:
          - elk
        
    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.1
        container_name: kibana
        ports:
          - 5601:5601
        volumes:
          - type: bind
            source: ./elk/kibana/kibana.yml
            target: /usr/share/kibana/config/kibana.yml
            read_only: true
        networks:
          - elk
        depends_on: 
          - elasticsearch
      
    logstash:
        image: docker.elastic.co/logstash/logstash:7.5.1
        container_name: logstash
        ports:
          - 5000:5000
          - 9600:9600
        volumes:
          - type: bind
            source: ./elk/logstash/logstash.yml
            target: /usr/share/logstash/config/logstash.yml
            read_only: true
          - type: bind
            source: ./elk/logstash/logstash.conf
            target: /usr/share/logstash/config/logstash.conf
            read_only: true
        depends_on: 
          - elasticsearch

volumes:
    elasticsearch:

networks:
  elk:
    driver: bridge